# Welcome to Jekyll!
#
# About Theme
#
# Yet another theme for elegant writers with modern flat style and beautiful
# night/dark mode.
#
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

local: "ko-KR"
title: ENJOY DEV.
email: hjy2859@naver.com
github: https://github.com/ju-ju2

author: ju-ju2
copyright: Copyright 2023. ju-ju2 all rights reserved.

baseurl: "" # the subpath of your site, e.g. /blog
url: https://ju-ju2.github.io # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/images/favicons/favicon-juju.ico" # the favicon for your site
logo: "/assets/images/favicons/favicon-juju.ico"
yat:
  date_format: "%Y-%m-%d"

description: "개발 일짱이 되는 과정을 기록하는 공간"
og:image: "/assets/images/banners/juju-og-image.png"

# If you want more debug log, you can set true
# debug: false

# Google analytics
# google_analytics: "G-7MDN6XTS1E"

# If you want to generate website sitemap, you can set true
# sitemap: false

night_mode: "manual"

header_pages:
  - index.html
  - about.html
  - archives.html
  - categories.html
  - tags.html

# defaults:
#   home:
#     banner:
#       image: /assets/images/banners/juju2-banner.png
#       opacity: 1
#       background: "#000"
#       height: "100vh"
#       min_height: "38vh"

# Pagination setting
paginate: 5

# Disqus comments
# comments:
#   provider: "disqus"
# disqus:
#   shortname: "ju-ju2GitBlog"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

  naver_site_verification: "da06869244094d84a44e4eb3f34f99b5bc77707a"
